version: '3'

services:
   db:
     image: postgres
     volumes:
       - db:/var/lib/postgresql/data
     restart: always

   rails:
     depends_on:
       - db
     image: cadolfson/ecomm-rails
     command: "bundle exec rails server -e production -p 3000 -b 0.0.0.0"
     ports:
       - "3000:3000"
     
volumes:
    db: